#!/usr/bin/env bash
set -euo pipefail

# --- Helpers -----------------------------------------------------------------
usage() {
  cat <<'EOF'
Usage: setup.sh [-p|--proxy <proxy>]

Optional proxy formats:
  - socks5://127.0.0.1:1080
  - socks5 127.0.0.1 1080
  - 127.0.0.1:1080          (defaults to socks5)

Behavior:
  * If a proxy is provided: write /etc/proxychains.conf and use proxychains
    for all networked steps after proxychains is installed.
  * If no proxy is provided: do NOT install proxychains and run everything normally.
EOF
}

require_root() {
  if [[ ${EUID} -ne 0 ]]; then
    echo "This script must be run as root." >&2
    exit 1
  fi
}

parse_proxy() {
  # Input: $1 (possibly empty)
  # Output via globals: PROXY_TYPE, PROXY_HOST, PROXY_PORT (if proxy provided)
  local in="${1:-}"
  PROXY_TYPE=""
  PROXY_HOST=""
  PROXY_PORT=""

  [[ -z "$in" ]] && return 0

  # Normalize spaces
  in="$(echo "$in" | xargs)"

  if [[ "$in" =~ ^(socks4|socks5|http|https)://([^:]+):([0-9]+)$ ]]; then
    PROXY_TYPE="${BASH_REMATCH[1]}"
    PROXY_HOST="${BASH_REMATCH[2]}"
    PROXY_PORT="${BASH_REMATCH[3]}"
  elif [[ "$in" =~ ^(socks4|socks5|http|https)[[:space:]]+([^[:space:]]+)[[:space:]]+([0-9]+)$ ]]; then
    PROXY_TYPE="${BASH_REMATCH[1]}"
    PROXY_HOST="${BASH_REMATCH[2]}"
    PROXY_PORT="${BASH_REMATCH[3]}"
  elif [[ "$in" =~ ^([^:]+):([0-9]+)$ ]]; then
    PROXY_TYPE="socks5"
    PROXY_HOST="${BASH_REMATCH[1]}"
    PROXY_PORT="${BASH_REMATCH[2]}"
  else
    echo "Unrecognized proxy format: '$in'" >&2
    exit 1
  fi
}

write_proxychains_conf() {
  local type="$1" host="$2" port="$3"

  cat >/etc/proxychains.conf <<EOF
# Generated by setup.sh
strict_chain
quiet_mode
proxy_dns
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
${type} ${host} ${port}
EOF
}

run_net() {
  # Run command with or without proxychains, depending on PROXYCHAINS_CMD
  if [[ -n "${PROXYCHAINS_CMD:-}" ]]; then
    ${PROXYCHAINS_CMD} "$@"
  else
    "$@"
  fi
}

# --- Arg parsing --------------------------------------------------------------
PROXY_ARG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -p|--proxy)
      [[ $# -lt 2 ]] && { echo "Missing value for $1" >&2; exit 1; }
      PROXY_ARG="$2"; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1;;
  esac
done

require_root
parse_proxy "$PROXY_ARG"

# --- Decide on proxychains usage ---------------------------------------------
PROXYCHAINS_CMD=""

if [[ -n "${PROXY_HOST:-}" ]]; then
  echo "[*] Proxy provided: ${PROXY_TYPE} ${PROXY_HOST} ${PROXY_PORT}"
  # Install proxychains (unproxied) and write config, then use it afterwards.
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y proxychains4 || DEBIAN_FRONTEND=noninteractive apt-get install -y proxychains
  # Some distros name it proxychains4; prefer whichever exists.
  if command -v proxychains4 >/dev/null 2>&1; then
    PROXYCHAINS_CMD="proxychains4"
  else
    PROXYCHAINS_CMD="proxychains"
  fi
  write_proxychains_conf "$PROXY_TYPE" "$PROXY_HOST" "$PROXY_PORT"
  echo "[*] proxychains configured at /etc/proxychains.conf and will be used for networked steps."
else
  echo "[*] No proxy provided. Proceeding without proxychains."
fi

# --- Base packages (with proxy if configured) --------------------------------
run_net apt-get update -y
DEBIAN_FRONTEND=noninteractive run_net apt-get install -y zip unzip nginx curl wget ca-certificates git zsh gpg

# --- Install eza --------------------------------------------------------------
# We download, extract eza binary into /usr/local/bin
run_net wget -qO /tmp/eza.tar.gz https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz
tar xf /tmp/eza.tar.gz --strip-components=1 -C /usr/local/bin
rm -f /tmp/eza.tar.gz

# --- Install Docker engine & CLI ---------------------------------------------
install -m 0755 -d /etc/apt/keyrings
run_net curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

ARCH="$(dpkg --print-architecture)"
CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
echo "deb [arch=${ARCH} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${CODENAME} stable" \
  | tee /etc/apt/sources.list.d/docker.list >/dev/null

run_net apt-get update -y
DEBIAN_FRONTEND=noninteractive run_net apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# --- Install docker-compose (standalone shim) --------------------------------
run_net curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose

# --- Quality-of-life: eza alias for zsh --------------------------------------
ZSHRC="${HOME}/.zshrc"
if ! grep -q 'alias ls="eza ' "$ZSHRC" 2>/dev/null; then
  echo 'alias ls="eza --color=always --git --no-time --tree --level=1 -h"' >> "$ZSHRC"
fi

# --- Versions ----------------------------------------------------------------
clear
echo "== Versions =="
docker -v || true
docker-compose -v || true
nginx -v || true
zsh --version || true
eza --version || true

echo
echo "All done."
if [[ -n "${PROXYCHAINS_CMD:-}" ]]; then
  echo "Networked steps above used: ${PROXYCHAINS_CMD}"
fi
